"""
nse_universe.py
───────────────
Complete NSE stock universe used for scanning.
Includes: Nifty 50, Nifty Next 50, Nifty Midcap 150,
          Nifty Smallcap 250, and additional NSE listings.

Each entry: (SYMBOL, APPROX_CMP_INR, SECTOR)
CMP values are reference prices (early 2025) — actual live
prices are fetched from Twelve Data at scan time.
Only stocks with live CMP > configured threshold pass the filter.
"""

# fmt: off
NSE_UNIVERSE = [
    # ── NIFTY 50 ──────────────────────────────────────────────────────────
    ("RELIANCE",    2980,  "OIL & GAS"),
    ("TCS",         3920,  "IT"),
    ("INFY",        1780,  "IT"),
    ("HDFCBANK",    1685,  "BANK"),
    ("ICICIBANK",   1290,  "BANK"),
    ("SBIN",         845,  "BANK"),
    ("WIPRO",        560,  "IT"),
    ("AXISBANK",    1125,  "BANK"),
    ("LTIM",        5680,  "IT"),
    ("HCLTECH",     1920,  "IT"),
    ("BAJFINANCE",  7240,  "NBFC"),
    ("TITAN",       3480,  "FMCG"),
    ("KOTAKBANK",   1980,  "BANK"),
    ("MARUTI",     12400,  "AUTO"),
    ("SUNPHARMA",   1890,  "PHARMA"),
    ("NTPC",         378,  "POWER"),
    ("POWERGRID",    328,  "POWER"),
    ("TECHM",       1680,  "IT"),
    ("ULTRACEMCO", 10200,  "CEMENT"),
    ("ADANIPORTS",  1360,  "INFRA"),
    ("ADANIENT",    2680,  "INFRA"),
    ("BAJAJFINSV",  1620,  "NBFC"),
    ("NESTLEIND",   2480,  "FMCG"),
    ("DRREDDY",     6780,  "PHARMA"),
    ("DIVISLAB",    4980,  "PHARMA"),
    ("CIPLA",       1560,  "PHARMA"),
    ("EICHERMOT",   4900,  "AUTO"),
    ("HEROMOTOCO",  4780,  "AUTO"),
    ("BPCL",         548,  "OIL & GAS"),
    ("COALINDIA",    486,  "MINING"),
    ("GRASIM",      2680,  "CEMENT"),
    ("JSWSTEEL",     978,  "METAL"),
    ("HINDALCO",     682,  "METAL"),
    ("INDUSINDBK",   980,  "BANK"),
    ("LT",          3680,  "INFRA"),
    ("ASIANPAINT",  2980,  "PAINT"),
    ("BRITANNIA",   5480,  "FMCG"),
    ("TATACONSUM",  1080,  "FMCG"),
    ("HDFCLIFE",     780,  "INSURANCE"),
    ("SBILIFE",     1680,  "INSURANCE"),
    ("MM",          2980,  "AUTO"),
    ("BAJAJ-AUTO",  9800,  "AUTO"),
    ("TATAMOTORS",  1050,  "AUTO"),
    ("APOLLOHOSP",  6980,  "HEALTHCARE"),
    ("SHRIRAMFIN",  3280,  "NBFC"),
    ("LTTS",        5200,  "IT"),
    ("ONGC",         298,  "OIL & GAS"),
    ("IOC",          174,  "OIL & GAS"),
    ("BEL",          295,  "DEFENCE"),
    ("TATAPOWER",    480,  "POWER"),

    # ── NIFTY NEXT 50 ─────────────────────────────────────────────────────
    ("PIDILITIND",  2980,  "CHEM"),
    ("GODREJCP",    1280,  "FMCG"),
    ("HAVELLS",     1780,  "CAPITAL GOODS"),
    ("DABUR",        580,  "FMCG"),
    ("MARICO",       680,  "FMCG"),
    ("COLPAL",      2880,  "FMCG"),
    ("SIEMENS",     7200,  "CAPITAL GOODS"),
    ("ABB",         8600,  "CAPITAL GOODS"),
    ("BOSCHLTD",   38500,  "AUTO ANCILLARY"),
    ("MUTHOOTFIN",  2080,  "NBFC"),
    ("CHOLAFIN",    1480,  "NBFC"),
    ("MPHASIS",     2980,  "IT"),
    ("COFORGE",     7180,  "IT"),
    ("PERSISTENT",  5680,  "IT"),
    ("IRCTC",        878,  "INFRA"),
    ("TRENT",       6580,  "RETAIL"),
    ("DMART",       4280,  "RETAIL"),
    ("ICICIGI",     1980,  "INSURANCE"),
    ("ICICIPRULI",   780,  "INSURANCE"),
    ("BAJAJHLDNG",  9800,  "HOLDING"),
    ("SBICARD",      780,  "NBFC"),
    ("FEDERALBNK",   198,  "BANK"),
    ("AUBANK",       778,  "BANK"),
    ("MCDOWELL-N",  1080,  "FMCG"),
    ("ZOMATO",       268,  "INTERNET"),
    ("PAYTM",        920,  "FINTECH"),
    ("NYKAA",        198,  "RETAIL"),
    ("ANGELONE",    2980,  "BROKING"),
    ("KPITTECH",    1680,  "IT"),
    ("TATAELXSI",   7980,  "IT"),
    ("OFSS",        9800,  "IT"),

    # ── NIFTY MIDCAP 150 ──────────────────────────────────────────────────
    ("AUROPHARMA",  1280,  "PHARMA"),
    ("ALKEM",       5980,  "PHARMA"),
    ("TORNTPHARM",  3480,  "PHARMA"),
    ("LUPIN",       2180,  "PHARMA"),
    ("GLENMARK",    1480,  "PHARMA"),
    ("IPCALAB",     1580,  "PHARMA"),
    ("NATCOPHARM",  1480,  "PHARMA"),
    ("AJANTPHARMA", 2980,  "PHARMA"),
    ("GRANULES",     598,  "PHARMA"),
    ("JUBLFOOD",     680,  "QSR"),
    ("CROMPTON",     378,  "CONSUMER"),
    ("VOLTAS",      1680,  "CONSUMER"),
    ("BLUESTAR",    1980,  "CONSUMER"),
    ("WHIRLPOOL",   1680,  "CONSUMER"),
    ("SYMPHONY",    1280,  "CONSUMER"),
    ("AMBER",       4280,  "CONSUMER"),
    ("DIXON",      14800,  "ELECTRONICS"),
    ("KAYNES",      4800,  "ELECTRONICS"),
    ("APLAPOLLO",   1680,  "METAL"),
    ("RAMCOCEM",     898,  "CEMENT"),
    ("SHREECEM",   28500,  "CEMENT"),
    ("ACC",         2480,  "CEMENT"),
    ("AMBUJACEM",    628,  "CEMENT"),
    ("JKCEMENT",    4580,  "CEMENT"),
    ("DALMIACEM",   1980,  "CEMENT"),
    ("JSWSTEEL",     978,  "METAL"),
    ("HINDZINC",     728,  "METAL"),
    ("VEDL",         498,  "METAL"),
    ("WELCORP",      678,  "METAL"),
    ("RATNAMANI",   3480,  "METAL"),
    ("TIINDIA",     3980,  "AUTO ANCILLARY"),
    ("THERMAX",     5980,  "CAPITAL GOODS"),
    ("CUMMINSIND",  3980,  "CAPITAL GOODS"),
    ("GRINDWELL",   2380,  "CAPITAL GOODS"),
    ("SCHAEFFLER",  4280,  "AUTO ANCILLARY"),
    ("TIMKEN",      3280,  "AUTO ANCILLARY"),
    ("SKFINDIA",    5680,  "AUTO ANCILLARY"),
    ("ELGIEQUIP",    898,  "CAPITAL GOODS"),
    ("NCC",          298,  "INFRA"),
    ("HEXAWARE",    1148,  "IT"),
    ("CYIENT",      1980,  "IT"),
    ("KFIN",        1248,  "FINTECH"),
    ("CAMS",        4380,  "FINTECH"),
    ("CDSL",        1980,  "CAPITAL MARKETS"),
    ("BSE",         5680,  "CAPITAL MARKETS"),
    ("MCX",         6980,  "CAPITAL MARKETS"),
    ("IRFC",         228,  "NBFC"),
    ("PFC",          498,  "NBFC"),
    ("RECLTD",       578,  "NBFC"),
    ("HUDCO",        248,  "NBFC"),
    ("CANFINHOME",   778,  "NBFC"),
    ("MFSL",        1180,  "INSURANCE"),
    ("PNBHOUSING",  1180,  "NBFC"),
    ("LICHSGFIN",    698,  "NBFC"),
    ("AAVAS",       1880,  "NBFC"),
    ("MANAPPURAM",   198,  "NBFC"),
    ("BANDHANBNK",   198,  "BANK"),
    ("IDFCFIRSTB",    95,  "BANK"),
    ("RAYMOND",     1980,  "TEXTILES"),
    ("TRENT",       6580,  "RETAIL"),
    ("BATA",        1480,  "RETAIL"),
    ("METRO",       1180,  "RETAIL"),
    ("CAMPUS",       298,  "RETAIL"),
    ("RELAXO",       898,  "RETAIL"),
    ("INDHOTEL",     680,  "HOSPITALITY"),
    ("EIHOTEL",      278,  "HOSPITALITY"),
    ("CHALET",       898,  "HOSPITALITY"),

    # ── NIFTY SMALLCAP 250 & ADDITIONAL NSE ───────────────────────────────
    ("ZYDUSLIFE",   1080,  "PHARMA"),
    ("WOCKPHARMA",   928,  "PHARMA"),
    ("BIOCON",       328,  "PHARMA"),
    ("LAURUSLABS",   568,  "PHARMA"),
    ("SOLARINDS",   9280,  "DEFENCE"),
    ("JBCHEPHARM",  1980,  "PHARMA"),
    ("SHILPAMED",    780,  "HEALTHCARE"),
    ("VINATIORGA",  1980,  "CHEM"),
    ("DEEPAKFERT",  1280,  "CHEM"),
    ("DEEPAKNITRI", 2980,  "CHEM"),
    ("ATUL",        7680,  "CHEM"),
    ("NAVINFLUOR",  3980,  "CHEM"),
    ("SRF",         2980,  "CHEM"),
    ("AARTI",        698,  "CHEM"),
    ("VINATI",      1980,  "CHEM"),
    ("ALKYLAMINE",  2480,  "CHEM"),
    ("ROSSARI",      898,  "CHEM"),
    ("FINEORG",     5480,  "CHEM"),
    ("GALAXSURF",   3480,  "CHEM"),
    ("CLEAN",       1680,  "CHEM"),
    ("TATACHEM",    1080,  "CHEM"),
    ("COROMANDEL",  1480,  "AGROCHEM"),
    ("PIIND",       3780,  "AGROCHEM"),
    ("BAYER",       6480,  "AGROCHEM"),
    ("DHANUKA",     1180,  "AGROCHEM"),
    ("GUJGAS",       498,  "OIL & GAS"),
    ("MGL",         1180,  "OIL & GAS"),
    ("IGL",          498,  "OIL & GAS"),
    ("ATGL",         898,  "OIL & GAS"),
    ("GAIL",         228,  "OIL & GAS"),
    ("PETRONET",     368,  "OIL & GAS"),
    ("ADANIGREEN",  1980,  "POWER"),
    ("ADANITRANS",  1180,  "POWER"),
    ("TORNTPOWER",  1680,  "POWER"),
    ("KALPATPOWR",   898,  "POWER"),
    ("KEC",          898,  "CAPITAL GOODS"),
    ("GRSE",        1980,  "DEFENCE"),
    ("MAZAGON",     2980,  "DEFENCE"),
    ("HAL",         4180,  "DEFENCE"),
    ("BDL",         1980,  "DEFENCE"),
    ("BEML",        4980,  "DEFENCE"),
    ("BHEL",         248,  "CAPITAL GOODS"),
    ("LALPATHLAB",  2780,  "HEALTHCARE"),
    ("METROPOLIS",  2180,  "HEALTHCARE"),
    ("THYROCARE",    698,  "HEALTHCARE"),
    ("FORTIS",       698,  "HEALTHCARE"),
    ("NARAYAN",     1180,  "HEALTHCARE"),
    ("MAXHEALTH",    998,  "HEALTHCARE"),
    ("INDIAMART",   2980,  "INTERNET"),
    ("JUSTDIAL",    1080,  "INTERNET"),
    ("NAUKRI",      6980,  "INTERNET"),
    ("POLICYBZR",   1880,  "INSURANCE"),
    ("MAPMYINDIA",  1480,  "INTERNET"),
    ("NAZARA",       998,  "GAMING"),
    ("RATEGAIN",     698,  "IT"),
    ("MASTEK",      2480,  "IT"),
    ("SONATSOFTW",   898,  "IT"),
    ("ZENSAR",       698,  "IT"),
    ("MPSLTD",      1580,  "IT"),
    ("NEWGEN",      1480,  "IT"),
    ("TANLA",        698,  "IT"),
    ("INTELLECT",    898,  "FINTECH"),
    ("NETWEB",      2380,  "IT"),
    ("KSOLVES",     1280,  "IT"),
    ("BIRLASOFT",    798,  "IT"),
    ("DATAMATICS",   598,  "IT"),
    ("ROUTE",       1980,  "IT"),
    ("PVRINOX",     1480,  "MEDIA"),
    ("ZEEL",         148,  "MEDIA"),
    ("SAREGAMA",     498,  "MEDIA"),
    ("TIPS",        2980,  "MEDIA"),
    ("CONCOR",       998,  "LOGISTICS"),
    ("MAHLOG",      1480,  "LOGISTICS"),
    ("TCI",         1280,  "LOGISTICS"),
    ("BLUEDART",    7980,  "LOGISTICS"),
    ("VRL",          598,  "LOGISTICS"),
    ("VARROC",       798,  "AUTO ANCILLARY"),
    ("MINDA",       1080,  "AUTO ANCILLARY"),
    ("ENDURANCE",   2180,  "AUTO ANCILLARY"),
    ("SUPRAJIT",     498,  "AUTO ANCILLARY"),
    ("GABRIEL",      298,  "AUTO ANCILLARY"),
    ("TVSMOTORS",   2480,  "AUTO"),
    ("ROYALENF",    4980,  "AUTO"),
    ("ESCORTS",     3980,  "AUTO"),
    ("SHOPERSTOP",   798,  "RETAIL"),
    ("VMART",       2580,  "RETAIL"),
    ("JYOTHYLAB",    478,  "FMCG"),
    ("EMAMILTD",     698,  "FMCG"),
    ("KANSAINER",    698,  "PAINT"),
    ("BERGER",       678,  "PAINT"),
    ("AKZO",        3580,  "PAINT"),
    ("INDIGO",      4280,  "AVIATION"),
    ("MRF",       128000,  "AUTO ANCILLARY"),
    ("PAGEIND",    38500,  "RETAIL"),
    ("HONAUT",     48000,  "CAPITAL GOODS"),
    ("GILLETTE",    8980,  "FMCG"),
    ("PFIZER",      5880,  "PHARMA"),
    ("SANOFI",      8980,  "PHARMA"),
    ("ABBOTINDIA", 28000,  "PHARMA"),
    ("LAXMIMACH",  16800,  "CAPITAL GOODS"),
    ("NEULAND",    14800,  "PHARMA"),
    ("JCHAC",       5200,  "CONSUMER"),
    ("CERA",        8980,  "CONSUMER"),
    ("KAJARIA",     1380,  "CONSUMER"),
    ("SOLARA",      1280,  "PHARMA"),
    ("NIACL",        198,  "INSURANCE"),
    ("STARHEALTH",   568,  "INSURANCE"),
    ("GICRE",        478,  "INSURANCE"),
    ("SBFC",          98,  "NBFC"),
    ("CREDITACC",   1480,  "NBFC"),
    ("CRISIL",      4980,  "RATING"),
    ("ICRA",        5480,  "RATING"),
    ("CARERATING",   998,  "RATING"),
    ("ACTION",      1880,  "RETAIL"),
    ("WESTLIFE",     898,  "QSR"),
    ("DEVYANI",      198,  "QSR"),
    ("SAPPHIRE",    1380,  "QSR"),
    ("BARBEQUE",    1080,  "QSR"),
]
# fmt: on

# Deduplicate by symbol
_seen: set = set()
_deduped = []
for entry in NSE_UNIVERSE:
    if entry[0] not in _seen:
        _seen.add(entry[0])
        _deduped.append(entry)
NSE_UNIVERSE = _deduped


def get_universe(cmp_min: float = 500.0) -> list:
    """Return [(symbol, base_cmp, sector)] with base_cmp >= cmp_min."""
    return [e for e in NSE_UNIVERSE if e[1] >= cmp_min]


def all_symbols(cmp_min: float = 500.0) -> list[str]:
    return [e[0] for e in get_universe(cmp_min)]


SECTOR_LIST = sorted({e[2] for e in NSE_UNIVERSE})
